github: [devinschumacher]

open_collective: devinschumacher

custom: [
"https://orangepornvideos.net/youporn-video-downloader",
"https://serpdownloaders.github.io/youporn-video-downloader",
"https://serp.co/products/youporn-video-downloader/reviews/",
"https://downloadingfreevideo.com/youporn-video-downloader",
]
